/**
 * Food photography brief (D-038: photography chosen by the product owner,
 * 2026-09-24). One 4:3 master per recipe. The app crops it to a 16:9 hero
 * and a 1:1 thumbnail, so keep the dish centred with room around it.
 *
 * Plain data with no React Native imports: `scripts/meal-photos.ts` turns it
 * into the prompt file and the checklist.
 */

export const PHOTO_SPEC = {
  master: { width: 1600, height: 1200, maxKB: 500, formats: ['jpg', 'jpeg', 'png'] as const },
  style:
    'Editorial food photograph, 3/4 view from about 45 degrees, soft window light from the upper left, matte stoneware on warm natural linen, shallow depth of field focused on the main protein, a portion for one person, no hands, no text, no brand packaging, warm neutral colour grade, 4:3 frame with the dish centred and 15% breathing room on every side.',
  rules: [
    'Show only ingredients that are in the recipe. Garnish only with recipe ingredients.',
    'One dish per photo, in the vessel named in the brief.',
    'Same light, surface and grade across every shot. Reshoot any image that breaks the set.',
    'Generated stills are labelled "Illustrative photo" in the About sheet and store listing. A person checks every image against the ingredient list before it ships.',
  ],
} as const;

export type Shot = { recipeId: string; vessel: string; prompt: string };

export const SHOTS: Shot[] = [
  { recipeId: 'd_chicken_rice_bowls', vessel: 'deep cream bowl', prompt: 'Garlic-glazed chicken pieces, jasmine rice and broccoli florets in a deep cream stoneware bowl.' },
  { recipeId: 'd_turkey_taco_skillet', vessel: 'cast-iron skillet', prompt: 'Ground turkey with black beans, bell peppers and onion in a cast-iron skillet, spoon of salsa on top, warm corn tortillas folded beside it.' },
  { recipeId: 'd_sheet_pan_salmon', vessel: 'sheet pan', prompt: 'One roasted salmon fillet with halved baby potatoes and green beans on a lightly used metal sheet pan, lemon slices.' },
  { recipeId: 'd_shrimp_stir_fry', vessel: 'shallow bowl', prompt: 'Shrimp and mixed stir-fry vegetables in a glossy garlic-soy sauce over brown rice in a shallow bowl.' },
  { recipeId: 'd_beef_broccoli', vessel: 'shallow bowl', prompt: 'Browned ground beef and broccoli in a garlic-soy sauce over jasmine rice in a shallow bowl.' },
  { recipeId: 'd_chicken_fajitas', vessel: 'sheet pan + tortillas', prompt: 'Chili-rubbed chicken strips with red, yellow and green peppers and onion on a sheet pan, flour tortillas, a small bowl of Greek yogurt and lime wedges beside it.' },
  { recipeId: 'd_turkey_meatball_pasta', vessel: 'wide pasta bowl', prompt: 'Pasta with marinara, five turkey meatballs and wilted baby spinach in a wide dark-blue pasta bowl, finely grated parmesan.' },
  { recipeId: 'd_egg_fried_rice', vessel: 'shallow bowl', prompt: 'Brown-rice fried rice with scrambled egg, edamame and mixed vegetables in a shallow bowl.' },
  { recipeId: 'd_greek_chicken_salad', vessel: 'wide salad bowl', prompt: 'Sliced seared chicken thighs over baby spinach, cucumber, halved cherry tomatoes and crumbled feta in a wide bowl, lemon wedge, olive oil.' },
  { recipeId: 'd_turkey_lettuce_wraps', vessel: 'platter', prompt: 'Butter-lettuce cups filled with garlicky ground turkey and shredded carrot on a platter, lime wedges.' },
  { recipeId: 'd_tofu_chickpea_curry', vessel: 'curry bowl', prompt: 'Golden red-curry coconut sauce with tofu cubes, chickpeas and wilted spinach in a sage-green bowl, jasmine rice on the side.' },
  { recipeId: 'd_sausage_peppers_potatoes', vessel: 'sheet pan', prompt: 'Sliced chicken sausage with roasted bell peppers, onion and baby potatoes on a sheet pan.' },
  { recipeId: 'd_sausage_white_beans', vessel: 'skillet', prompt: 'Browned chicken sausage coins with white beans, garlic and wilted spinach in a skillet.' },
  { recipeId: 'd_sirloin_green_beans', vessel: 'plate', prompt: 'Sliced seared sirloin steak, pink in the middle, with garlicky green beans on a matte plate.' },
  { recipeId: 'd_salmon_quinoa', vessel: 'plate', prompt: 'Lemon salmon fillet on quinoa with wilted baby spinach on a matte plate, lemon slice.' },
  { recipeId: 'd_batch_turkey_chili', vessel: 'pot + bowl', prompt: 'Turkey and black bean chili with tomatoes and peppers in a bowl, the pot softly out of focus behind it.' },
  { recipeId: 'd_batch_roast_thighs', vessel: 'roasting tray', prompt: 'Roast chicken thighs with crisp skin, sweet potato chunks and broccoli on a roasting tray.' },
  { recipeId: 'l_chicken_bean_bowls', vessel: 'lunch container', prompt: 'Lunch container with chicken, jasmine rice, black beans and a scoop of salsa in neat sections.' },
  { recipeId: 'l_yogurt_chicken_wraps', vessel: 'board', prompt: 'Two halves of a Greek-yogurt chicken salad wrap with cucumber and spinach, cut to show the filling, on a wooden board, lemon.' },
  { recipeId: 'l_egg_quinoa_boxes', vessel: 'lunch container', prompt: 'Lunch container with quinoa, halved hard-boiled eggs, edamame and cherry tomatoes in sections.' },
  { recipeId: 'l_turkey_hummus_boxes', vessel: 'lunch container', prompt: 'Lunch container with rolled turkey slices, hummus, cucumber, shredded carrot and whole-wheat pita triangles.' },
  { recipeId: 'l_tuna_white_bean_salad', vessel: 'bowl', prompt: 'Tuna and white bean salad with baby spinach and cherry tomatoes in a bowl, lemon and olive oil dressing.' },
  { recipeId: 'd_chicken_burrito_bowls', vessel: 'shallow bowl', prompt: 'Seasoned chicken pieces over jasmine rice with black beans, corn and salsa in a shallow bowl, lime wedge.' },
  { recipeId: 'd_chicken_pesto_pasta', vessel: 'wide pasta bowl', prompt: 'Pasta tossed with basil pesto, chicken pieces, halved cherry tomatoes and wilted spinach in a wide pasta bowl.' },
  { recipeId: 'd_chicken_coconut_curry', vessel: 'curry bowl', prompt: 'Chicken in a golden coconut-tomato curry with chopped cilantro in a bowl, jasmine rice on the side.' },
  { recipeId: 'd_honey_garlic_chicken', vessel: 'shallow bowl', prompt: 'Glossy honey-garlic chicken strips and green beans over brown rice in a shallow bowl.' },
  { recipeId: 'd_chicken_cauli_fried_rice', vessel: 'shallow bowl', prompt: 'Cauliflower fried rice with chicken, scrambled egg, peas, carrot and sliced green onion in a shallow bowl.' },
  { recipeId: 'd_chicken_zucchini_skillet', vessel: 'skillet', prompt: 'Chicken pieces with zucchini half-moons and blistered cherry tomatoes in a skillet, grated parmesan on top.' },
  { recipeId: 'd_chicken_avocado_salad', vessel: 'wide salad bowl', prompt: 'Sliced chili-lime chicken over chopped romaine with avocado, cherry tomatoes and corn in a wide bowl, lime wedge.' },
  { recipeId: 'd_peanut_chicken_noodles', vessel: 'shallow bowl', prompt: 'Rice noodles in peanut sauce with chicken strips, snap peas and shredded carrot in a shallow bowl, lime wedge.' },
  { recipeId: 'd_cashew_chicken', vessel: 'shallow bowl', prompt: 'Cashew chicken with broccoli and bell pepper in a glossy soy-honey sauce, jasmine rice alongside.' },
  { recipeId: 'd_greek_chicken_couscous', vessel: 'shallow bowl', prompt: 'Sliced chicken over couscous with cucumber, cherry tomatoes, kalamata olives and crumbled feta, lemon wedge.' },
  { recipeId: 'd_chicken_enchilada_skillet', vessel: 'cast-iron skillet', prompt: 'Chicken, black beans, corn and tortilla strips in red enchilada sauce with melted cheddar in a cast-iron skillet.' },
  { recipeId: 'd_dijon_chicken_mushrooms', vessel: 'plate', prompt: 'Seared chicken cutlets in a Dijon pan sauce with mushrooms and wilted spinach on a matte plate.' },
  { recipeId: 'd_chicken_shawarma_pitas', vessel: 'sheet pan + pita', prompt: 'Spiced chicken and onion strips on a sheet pan, warm pita and a small bowl of cucumber yogurt sauce beside it.' },
  { recipeId: 'd_sausage_kale_soup', vessel: 'soup bowl', prompt: 'Chicken sausage coins, white beans, tomato and kale in broth in a deep soup bowl.' },
  { recipeId: 'd_sausage_zucchini_pasta', vessel: 'wide pasta bowl', prompt: 'Pasta with sliced chicken sausage, zucchini and marinara in a wide pasta bowl, grated parmesan.' },
  { recipeId: 'd_sausage_sweet_potato_pan', vessel: 'sheet pan', prompt: 'Browned chicken sausage, roasted sweet potato cubes and broccoli on a sheet pan.' },
  { recipeId: 'd_turkey_burgers_slaw', vessel: 'board', prompt: 'Turkey burger on a toasted whole-wheat bun with Dijon, creamy lemon slaw on the side, on a wooden board.' },
  { recipeId: 'd_turkey_burger_bowls', vessel: 'wide salad bowl', prompt: 'Sliced turkey burger patties over romaine with cherry tomatoes, thin onion and avocado, Dijon dressing.' },
  { recipeId: 'd_turkey_sweet_potato_skillet', vessel: 'skillet', prompt: 'Ground turkey with diced sweet potato, black beans and wilted spinach in a skillet.' },
  { recipeId: 'd_ginger_turkey_rice_bowls', vessel: 'shallow bowl', prompt: 'Ginger ground turkey and snap peas over brown rice with sliced green onion in a shallow bowl.' },
  { recipeId: 'd_turkey_taco_salad', vessel: 'wide salad bowl', prompt: 'Chopped romaine topped with seasoned turkey, black beans, avocado, cheddar and salsa in a wide bowl.' },
  { recipeId: 'd_turkey_cabbage_skillet', vessel: 'skillet', prompt: 'Ground turkey with shredded cabbage, carrot, ginger and green onion in a skillet.' },
  { recipeId: 'd_beef_tacos_slaw', vessel: 'platter', prompt: 'Three corn-tortilla beef tacos topped with lime slaw and salsa on a platter.' },
  { recipeId: 'd_cheeseburgers_potatoes', vessel: 'plate', prompt: 'Cheeseburger with romaine on a whole-wheat bun, roasted baby potatoes beside it on a matte plate.' },
  { recipeId: 'd_steak_fajita_bowls', vessel: 'shallow bowl', prompt: 'Sliced seared steak with peppers and onions over rice, avocado and lime wedge, in a shallow bowl.' },
  { recipeId: 'd_steak_mushroom_salad', vessel: 'wide salad bowl', prompt: 'Sliced steak over baby spinach with seared mushrooms and cherry tomatoes in a wide bowl.' },
  { recipeId: 'd_ginger_beef_snap_peas', vessel: 'shallow bowl', prompt: 'Thin ginger beef strips with snap peas and bell pepper over jasmine rice in a shallow bowl.' },
  { recipeId: 'd_korean_beef_cauli_rice', vessel: 'shallow bowl', prompt: 'Sweet-savory ground beef over cauliflower rice with sliced cucumber and green onion in a shallow bowl.' },
  { recipeId: 'd_beef_zucchini_feta', vessel: 'skillet', prompt: 'Ground beef with zucchini and tomatoes in a skillet, crumbled feta on top.' },
  { recipeId: 'd_taco_sweet_potatoes', vessel: 'plate', prompt: 'Two split sweet potatoes filled with taco beef, Greek yogurt and salsa on a matte plate.' },
  { recipeId: 'd_sirloin_asparagus_potatoes', vessel: 'plate', prompt: 'Sliced sirloin, pink in the middle, with roasted asparagus and baby potatoes on a matte plate.' },
  { recipeId: 'd_dijon_pork_tenderloin', vessel: 'sheet pan', prompt: 'Dijon-glazed pork tenderloin medallions with roasted sweet potato cubes and green beans on a sheet pan.' },
  { recipeId: 'd_garlic_pork_chops_broccoli', vessel: 'plate', prompt: 'Seared paprika pork chop with garlicky broccoli on a matte plate.' },
  { recipeId: 'd_pork_veggie_stir_fry', vessel: 'shallow bowl', prompt: 'Thin pork strips with mixed stir-fry vegetables over brown rice in a shallow bowl.' },
  { recipeId: 'd_pork_chops_cauliflower', vessel: 'plate', prompt: 'Smoky seared pork chop with roasted cauliflower and wilted spinach on a matte plate.' },
  { recipeId: 'd_pork_couscous_zucchini', vessel: 'plate', prompt: 'Seared pork medallions with zucchini and lemony couscous on a matte plate.' },
  { recipeId: 'd_salmon_rice_bowls', vessel: 'shallow bowl', prompt: 'Glazed salmon cubes over brown rice with cucumber, avocado and green onion in a shallow bowl.' },
  { recipeId: 'd_dijon_salmon_asparagus', vessel: 'sheet pan', prompt: 'Dijon-topped salmon fillet with roasted asparagus and lemon on a sheet pan.' },
  { recipeId: 'd_salmon_tacos', vessel: 'platter', prompt: 'Corn-tortilla tacos with flaked chili salmon and avocado slaw on a platter, lime wedges.' },
  { recipeId: 'd_cod_tomatoes_olives', vessel: 'baking dish', prompt: 'Baked cod with blistered cherry tomatoes, zucchini and kalamata olives in a baking dish, lemon.' },
  { recipeId: 'd_cod_tacos', vessel: 'platter', prompt: 'Corn-tortilla tacos with flaked cod and creamy lime slaw on a platter.' },
  { recipeId: 'd_cod_coconut_curry', vessel: 'curry bowl', prompt: 'Cod pieces in red curry coconut sauce with bell pepper and spinach, jasmine rice alongside.' },
  { recipeId: 'd_lemon_cod_potatoes', vessel: 'sheet pan', prompt: 'Roasted cod fillet with baby potatoes and green beans on a sheet pan, lemon wedges.' },
  { recipeId: 'd_shrimp_tacos', vessel: 'platter', prompt: 'Chili-lime shrimp tacos on corn tortillas with slaw and avocado on a platter.' },
  { recipeId: 'd_garlic_shrimp_zucchini', vessel: 'skillet', prompt: 'Garlic shrimp with zucchini half-moons and cherry tomatoes in a skillet, lemon.' },
  { recipeId: 'd_shrimp_pesto_pasta', vessel: 'wide pasta bowl', prompt: 'Pasta with shrimp, basil pesto, spinach and cherry tomatoes in a wide pasta bowl.' },
  { recipeId: 'd_shrimp_red_curry', vessel: 'curry bowl', prompt: 'Shrimp and mixed vegetables in red curry coconut sauce, jasmine rice alongside.' },
  { recipeId: 'd_shrimp_quinoa_bowls', vessel: 'shallow bowl', prompt: 'Smoky shrimp over quinoa with black beans, corn and avocado in a shallow bowl, lime.' },
  { recipeId: 'd_shrimp_rice_noodles', vessel: 'shallow bowl', prompt: 'Rice noodles with shrimp, snap peas and shredded carrot in a shallow bowl, lime wedge.' },
  { recipeId: 'd_tuna_tomato_pasta', vessel: 'wide pasta bowl', prompt: 'Pasta with flaked tuna, blistered cherry tomatoes, spinach and garlic in a wide pasta bowl.' },
  { recipeId: 'd_tuna_avocado_rice_bowls', vessel: 'shallow bowl', prompt: 'Tuna over brown rice with sliced avocado, cucumber and green onion in a shallow bowl.' },
  { recipeId: 'd_tuna_melts', vessel: 'plate', prompt: 'Open-faced tuna melts with bubbling cheddar on whole-wheat toast, chopped romaine beside them.' },
  { recipeId: 'd_chickpea_shakshuka', vessel: 'cast-iron skillet', prompt: 'Eggs baked in spiced tomato and pepper sauce with chickpeas in a cast-iron skillet, warm pita.' },
  { recipeId: 'd_mushroom_feta_frittata', vessel: 'skillet', prompt: 'Spinach, mushroom and feta frittata in an oven-safe skillet, one wedge cut.' },
  { recipeId: 'd_egg_black_bean_tacos', vessel: 'platter', prompt: 'Corn tortillas with scrambled eggs, black beans, avocado and salsa on a platter.' },
  { recipeId: 'd_sweet_potato_egg_hash', vessel: 'skillet', prompt: 'Sweet potato and pepper hash with kale and two eggs set on top in a skillet.' },
  { recipeId: 'd_veggie_egg_scramble', vessel: 'plate', prompt: 'Soft scrambled eggs with mushrooms, spinach and cherry tomatoes, avocado slices, on a matte plate.' },
  { recipeId: 'd_cauli_egg_fried_rice', vessel: 'shallow bowl', prompt: 'Cauliflower fried rice with scrambled egg, edamame, carrot and green onion in a shallow bowl.' },
  { recipeId: 'd_tofu_broccoli_stir_fry', vessel: 'shallow bowl', prompt: 'Crispy tofu cubes and broccoli in a ginger-garlic glaze over brown rice in a shallow bowl.' },
  { recipeId: 'd_peanut_tofu_noodles', vessel: 'shallow bowl', prompt: 'Rice noodles in peanut sauce with crispy tofu, carrot and cucumber in a shallow bowl.' },
  { recipeId: 'd_tofu_scramble_tacos', vessel: 'platter', prompt: 'Corn tortillas filled with spiced tofu scramble, black beans and spinach, salsa on a platter.' },
  { recipeId: 'd_tempeh_sweet_potato_bowls', vessel: 'shallow bowl', prompt: 'Browned tempeh cubes, roasted sweet potato, lemony kale and quinoa in a shallow bowl.' },
  { recipeId: 'd_ginger_tempeh_snap_peas', vessel: 'shallow bowl', prompt: 'Ginger tempeh strips with snap peas and bell pepper over jasmine rice in a shallow bowl.' },
  { recipeId: 'd_tofu_cauliflower_curry', vessel: 'curry bowl', prompt: 'Tofu and cauliflower in a golden coconut curry with spinach over cauliflower rice.' },
  { recipeId: 'd_tofu_mushroom_lettuce_wraps', vessel: 'platter', prompt: 'Butter-lettuce cups filled with crumbled tofu and mushrooms, shredded carrot and green onion.' },
  { recipeId: 'd_black_bean_corn_tacos', vessel: 'platter', prompt: 'Black bean and corn tacos on corn tortillas with mashed avocado and salsa on a platter.' },
  { recipeId: 'd_red_lentil_dal', vessel: 'curry bowl', prompt: 'Golden red lentil dal with wilted spinach in a bowl, jasmine rice alongside.' },
  { recipeId: 'd_chickpea_spinach_curry', vessel: 'curry bowl', prompt: 'Chickpea and spinach tomato curry over brown rice in a bowl.' },
  { recipeId: 'd_pinto_burrito_bowls', vessel: 'shallow bowl', prompt: 'Pinto beans, rice, corn, romaine, avocado, cheddar and salsa in a shallow bowl.' },
  { recipeId: 'd_bean_spinach_quesadillas', vessel: 'board', prompt: 'Golden black bean and spinach quesadilla wedges on a wooden board, a small bowl of salsa.' },
  { recipeId: 'd_white_bean_kale_soup', vessel: 'soup bowl', prompt: 'White bean, kale, carrot and tomato soup in a deep soup bowl.' },
  { recipeId: 'd_chickpea_quinoa_bowls', vessel: 'shallow bowl', prompt: 'Chickpeas over quinoa with cucumber, cherry tomatoes, olives and crumbled feta, lemon wedge.' },
  { recipeId: 'd_white_bean_tomato_pasta', vessel: 'wide pasta bowl', prompt: 'Pasta with white beans, tomatoes and spinach in a wide pasta bowl, grated parmesan.' },
  { recipeId: 'd_sweet_potato_black_bean_bowls', vessel: 'shallow bowl', prompt: 'Roasted sweet potato cubes, black beans, quinoa and avocado over spinach in a shallow bowl, lime.' },
  { recipeId: 'd_lentil_tacos', vessel: 'platter', prompt: 'Spiced lentil tacos on corn tortillas with slaw, avocado and salsa on a platter.' },
  { recipeId: 'd_chickpea_zucchini_feta', vessel: 'skillet', prompt: 'Chickpeas with zucchini and softened cherry tomatoes in a skillet, crumbled feta.' },
  { recipeId: 'd_naan_pizzas', vessel: 'board', prompt: 'Two naan pizzas with marinara, melted mozzarella, mushrooms, pepper and spinach on a wooden board.' },
  { recipeId: 'd_turkey_marinara_rice_pasta', vessel: 'wide pasta bowl', prompt: 'Brown rice penne with turkey marinara and diced zucchini in a wide pasta bowl.' },
  { recipeId: 'd_chickpea_rice_pasta', vessel: 'wide pasta bowl', prompt: 'Brown rice pasta with chickpeas, tomatoes and spinach in a wide pasta bowl.' },
  { recipeId: 'd_batch_chicken_tortilla_soup', vessel: 'pot + bowl', prompt: 'Chicken tortilla soup with black beans and corn, crisp tortilla strips on top, the pot softly out of focus behind it.' },
  { recipeId: 'd_batch_lemon_chicken_rice_soup', vessel: 'pot + bowl', prompt: 'Lemon chicken and rice soup with carrots, celery and spinach in a bowl, the pot out of focus behind it.' },
  { recipeId: 'd_batch_salsa_chicken_tacos', vessel: 'baking dish + tacos', prompt: 'Shredded salsa chicken in a baking dish, two filled corn-tortilla tacos with slaw and avocado beside it.' },
  { recipeId: 'd_batch_chicken_fajita_cauli', vessel: 'meal-prep containers', prompt: 'Chicken fajita strips with peppers over cauliflower rice in glass containers, avocado and salsa on top of one.' },
  { recipeId: 'd_batch_turkey_stuffed_peppers', vessel: 'baking dish', prompt: 'Bell pepper halves stuffed with turkey, rice and tomato, melted cheddar on top, in a baking dish.' },
  { recipeId: 'd_batch_turkey_bolognese', vessel: 'pot + bowl', prompt: 'Pasta with turkey bolognese and parmesan in a bowl, the sauce pot out of focus behind it.' },
  { recipeId: 'd_batch_turkey_meatballs_quinoa', vessel: 'shallow bowl', prompt: 'Turkey meatballs in marinara with spinach over quinoa in a shallow bowl.' },
  { recipeId: 'd_batch_beef_bean_chili', vessel: 'pot + bowl', prompt: 'Beef and kidney bean chili with tomatoes and peppers in a bowl, the pot out of focus behind it.' },
  { recipeId: 'd_batch_beef_potato_stew', vessel: 'pot + bowl', prompt: 'Beef, mushroom, carrot and potato stew in a deep bowl, the pot out of focus behind it.' },
  { recipeId: 'd_batch_shepherds_pie', vessel: 'baking dish', prompt: 'Shepherd\'s pie with golden mashed-potato top, one scoop removed to show beef, peas and carrots.' },
  { recipeId: 'd_batch_pork_carnitas', vessel: 'platter', prompt: 'Crisp shredded pork carnitas tacos on corn tortillas with cilantro, salsa and lime on a platter.' },
  { recipeId: 'd_batch_roast_pork_cauliflower', vessel: 'sheet pan', prompt: 'Sliced roast pork tenderloin with roasted cauliflower and green beans on a sheet pan.' },
  { recipeId: 'd_batch_lentil_vegetable_soup', vessel: 'pot + bowl', prompt: 'Lentil vegetable soup with carrots, celery and spinach in a bowl, the pot out of focus behind it.' },
  { recipeId: 'd_batch_three_bean_chili', vessel: 'pot + bowl', prompt: 'Three-bean vegetarian chili with corn and peppers in a bowl, the pot out of focus behind it.' },
  { recipeId: 'd_batch_chickpea_sweet_potato_curry', vessel: 'curry bowl', prompt: 'Chickpea and sweet potato coconut curry with spinach in a bowl, jasmine rice alongside.' },
  { recipeId: 'd_batch_minestrone', vessel: 'pot + bowl', prompt: 'Minestrone with white beans, small pasta, zucchini and spinach in a bowl, parmesan, the pot out of focus behind it.' },
  { recipeId: 'd_batch_baked_ziti', vessel: 'baking dish', prompt: 'Spinach baked ziti with browned mozzarella in a baking dish, one portion lifted out.' },
  { recipeId: 'd_batch_black_bean_enchiladas', vessel: 'baking dish', prompt: 'Black bean enchilada bake with melted cheddar and red sauce in a baking dish, one square cut.' },
  { recipeId: 'l_chickpea_cucumber_salad', vessel: 'lunch container', prompt: 'Chickpea, cucumber, cherry tomato and olive salad in a lunch container.' },
  { recipeId: 'l_chickpea_salad_pitas', vessel: 'board', prompt: 'Whole-wheat pita halves filled with creamy chickpea salad and spinach on a wooden board.' },
  { recipeId: 'l_egg_salad_lettuce_cups', vessel: 'lunch container', prompt: 'Egg salad with celery beside butter-lettuce leaves in a lunch container.' },
  { recipeId: 'l_avocado_egg_salad', vessel: 'lunch container', prompt: 'Avocado egg salad with celery beside butter-lettuce leaves in a lunch container.' },
  { recipeId: 'l_turkey_avocado_wraps', vessel: 'board', prompt: 'Turkey, avocado, spinach and cucumber wrap cut in half on a wooden board.' },
  { recipeId: 'l_turkey_lettuce_rollups', vessel: 'lunch container', prompt: 'Turkey and avocado rolled in butter lettuce with cucumber sticks and shredded carrot in a lunch container.' },
  { recipeId: 'l_tuna_salad_lettuce_cups', vessel: 'lunch container', prompt: 'Lemony tuna salad with celery beside butter-lettuce leaves in a lunch container.' },
  { recipeId: 'l_tuna_edamame_rice_boxes', vessel: 'lunch container', prompt: 'Brown rice, tuna, edamame and sliced cucumber in neat sections of a lunch container.' },
  { recipeId: 'l_lemon_chicken_quinoa', vessel: 'lunch container', prompt: 'Sliced chicken over quinoa with cucumber, cherry tomatoes and spinach in a lunch container, lemon wedge.' },
  { recipeId: 'l_pesto_chicken_pasta_salad', vessel: 'lunch container', prompt: 'Pesto pasta salad with chicken, cherry tomatoes and spinach in a lunch container.' },
  { recipeId: 'l_peanut_noodle_salad', vessel: 'lunch container', prompt: 'Cold rice noodles in peanut dressing with edamame, carrot and cucumber in a lunch container.' },
  { recipeId: 'l_black_bean_quinoa_salad', vessel: 'lunch container', prompt: 'Black bean, corn, pepper and quinoa salad with cilantro in a lunch container, lime wedge.' },
  { recipeId: 'l_lentil_feta_salad', vessel: 'lunch container', prompt: 'Lentil salad with cucumber, cherry tomatoes and feta in a lunch container.' },
  { recipeId: 'l_lemony_lentil_carrot_salad', vessel: 'lunch container', prompt: 'Lemony lentil salad with shredded carrot and celery in a lunch container, spinach alongside.' },
  { recipeId: 'l_hummus_veggie_wraps', vessel: 'board', prompt: 'Hummus and crunchy vegetable wrap with feta, cut in half on a wooden board.' },
  { recipeId: 'l_hummus_quinoa_bowls', vessel: 'lunch container', prompt: 'Quinoa, chickpeas, cucumber and cherry tomatoes with a scoop of hummus in a lunch container.' },
  { recipeId: 'l_turkey_cheddar_sandwiches', vessel: 'board', prompt: 'Turkey and cheddar sandwich on whole-wheat bread with romaine, cut in half, carrots on the side.' },
  { recipeId: 'l_ginger_tofu_rice_bowls', vessel: 'lunch container', prompt: 'Ginger tofu and broccoli over brown rice in a lunch container.' },
  { recipeId: 'l_shrimp_avocado_salad', vessel: 'lunch container', prompt: 'Shrimp, avocado, corn and cherry tomato salad over romaine in a lunch container, lime wedge.' },
  { recipeId: 'l_chicken_cauli_rice_bowls', vessel: 'lunch container', prompt: 'Sliced chicken over cauliflower rice with black beans, salsa and avocado in a lunch container.' },
  { recipeId: 'l_batch_turkey_taco_bowls', vessel: 'lunch container', prompt: 'Seasoned turkey and black beans over rice with chopped romaine and salsa in a lunch container.' },
  { recipeId: 'l_batch_red_lentil_soup', vessel: 'jar', prompt: 'Red lentil and carrot soup in a glass jar with a lemon wedge beside it.' },
  { recipeId: 'l_batch_chicken_sweet_potato_boxes', vessel: 'lunch container', prompt: 'Sliced roast chicken, sweet potato cubes and green beans in sections of a lunch container.' },
  { recipeId: 'l_batch_beef_broccoli_rice', vessel: 'lunch container', prompt: 'Ground beef and broccoli over jasmine rice in a lunch container.' },
  { recipeId: 'l_batch_chickpea_curry_jars', vessel: 'jar', prompt: 'Chickpea tomato-coconut curry with spinach over brown rice in a glass jar.' },
  { recipeId: 'l_italian_pasta_salad', vessel: 'lunch container', prompt: 'Italian pasta salad with white beans, cherry tomatoes, olives, mozzarella and spinach in a lunch container.' },
  { recipeId: 'l_batch_egg_veggie_bites', vessel: 'lunch container', prompt: 'Four egg and vegetable bites with cheddar and carrot sticks in a lunch container.' },
  { recipeId: 'l_tempeh_kale_quinoa', vessel: 'lunch container', prompt: 'Tempeh cubes, massaged kale, carrot and quinoa in a lunch container, lemon wedge.' },
  { recipeId: 'l_chicken_hummus_pitas', vessel: 'board', prompt: 'Whole-wheat pita filled with hummus, sliced chicken, cucumber and cherry tomatoes on a wooden board.' },
  { recipeId: 'l_batch_bean_cheese_burritos', vessel: 'board', prompt: 'A bean, rice and cheese burrito cut in half on a wooden board, a small cup of salsa.' },
  { recipeId: 'l_sweet_potato_black_bean_boxes', vessel: 'lunch container', prompt: 'Roasted sweet potato cubes and black beans with spinach and salsa in a lunch container.' },
  { recipeId: 'l_tuna_pasta_salad', vessel: 'lunch container', prompt: 'Tuna pasta salad with peas and celery in a creamy lemon dressing in a lunch container.' },
];

export const fullPrompt = (s: Shot) => `${s.prompt} ${PHOTO_SPEC.style}`;
