/**
 * Meal photos (D-038). Put one 4:3 master per recipe in assets/meals/,
 * named by recipe id (e.g. d_sheet_pan_salmon.jpg), then run `npm run photos`.
 *
 * It does three things:
 * - validates each file (known recipe, JPEG/PNG, at least 1600×1200, 4:3 ±2%, ≤ 500 KB);
 * - regenerates src/photos/mealPhotos.ts, the require() map the app uses;
 * - writes assets/meals/prompts.json and docs/release/food-photography-checklist.md.
 *
 * `npm run photos -- --check` fails unless every recipe has a valid photo.
 * That's a release gate, not a CI gate.
 */
import { RECIPES } from '@weekwell/domain';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';
import { PHOTO_SPEC, SHOTS, fullPrompt } from '../src/photos/brief.ts';

const ROOT = join(import.meta.dirname, '..');
const DIR = join(ROOT, 'assets/meals');
const check = process.argv.includes('--check');

export function imageSize(buf: Buffer): { width: number; height: number } | null {
  // PNG: IHDR right after the signature.
  if (buf.length > 24 && buf.readUInt32BE(0) === 0x89504e47) return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
  // JPEG: walk markers to the first start-of-frame.
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let i = 2;
    while (i + 9 < buf.length) {
      if (buf[i] !== 0xff) return null;
      const marker = buf[i + 1]!;
      const len = buf.readUInt16BE(i + 2);
      if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
      i += 2 + len;
    }
  }
  return null;
}

const ids = new Set(RECIPES.map((r) => r.id));
const problems: string[] = [];
const briefed = new Set(SHOTS.map((s) => s.recipeId));
for (const id of ids) if (!briefed.has(id)) problems.push(`brief: no shot for recipe ${id} in src/photos/brief.ts`);
for (const id of briefed) if (!ids.has(id)) problems.push(`brief: shot for unknown recipe ${id}`);
const found = new Map<string, string>();
for (const f of existsSync(DIR) ? readdirSync(DIR) : []) {
  const ext = extname(f).slice(1).toLowerCase();
  if (f === 'prompts.json' || f === 'README.md' || f.startsWith('.')) continue;
  const id = f.slice(0, -(ext.length + 1));
  if (!(PHOTO_SPEC.master.formats as readonly string[]).includes(ext)) { problems.push(`${f}: use .jpg or .png`); continue; }
  if (!ids.has(id)) { problems.push(`${f}: no recipe with id "${id}"`); continue; }
  if (found.has(id)) { problems.push(`${f}: a second photo for ${id}`); continue; }
  const buf = readFileSync(join(DIR, f));
  const size = imageSize(buf);
  const kb = Math.round(statSync(join(DIR, f)).size / 1024);
  if (!size) { problems.push(`${f}: couldn’t read the image size`); continue; }
  if (size.width < PHOTO_SPEC.master.width || size.height < PHOTO_SPEC.master.height) problems.push(`${f}: ${size.width}×${size.height}, needs at least ${PHOTO_SPEC.master.width}×${PHOTO_SPEC.master.height}`);
  else if (Math.abs(size.width / size.height - 4 / 3) > 0.02 * (4 / 3)) problems.push(`${f}: ${size.width}×${size.height} isn’t 4:3`);
  else if (kb > PHOTO_SPEC.master.maxKB) problems.push(`${f}: ${kb} KB, keep it under ${PHOTO_SPEC.master.maxKB} KB (JPEG quality ~80)`);
  else found.set(id, f);
}

const entries = [...found.entries()].sort(([a], [b]) => a.localeCompare(b));
writeFileSync(
  join(ROOT, 'src/photos/mealPhotos.ts'),
  `// Generated by \`npm run photos\` from assets/meals/. Do not edit by hand.\nexport const MEAL_PHOTOS: Record<string, number> = {${entries.length ? '\n' + entries.map(([id, f]) => `  ${id}: require('../../assets/meals/${f}'),`).join('\n') + '\n' : ''}};\n`,
);
writeFileSync(join(DIR, 'prompts.json'), JSON.stringify(SHOTS.map((s) => ({ file: `${s.recipeId}.jpg`, vessel: s.vessel, prompt: fullPrompt(s) })), null, 2) + '\n');

const name = new Map(RECIPES.map((r) => [r.id, r.name]));
const rows = SHOTS.map((s) => `| ${found.has(s.recipeId) ? '✅' : '⬜'} | \`${s.recipeId}.jpg\` | ${name.get(s.recipeId)} | ${s.vessel} | ${s.prompt} |`);
writeFileSync(
  join(ROOT, 'docs/release/food-photography-checklist.md'),
  `# Food photography checklist (D-038)\n\nGenerated by \`npm run photos\`: ${found.size} of ${RECIPES.length} recipes have an approved photo. The app switches from the illustrated plates to photos only when all ${RECIPES.length} are present, so the two styles are never mixed.\n\n## Spec\n\n- One master per recipe: ${PHOTO_SPEC.master.width}×${PHOTO_SPEC.master.height} or larger, 4:3, JPEG or PNG, under ${PHOTO_SPEC.master.maxKB} KB, saved as \`apps/mobile/assets/meals/<recipe id>.jpg\`.\n- The app crops the master to a 16:9 hero and a 1:1 thumbnail. Keep the dish centred.\n- Style (append to every prompt): ${PHOTO_SPEC.style}\n${PHOTO_SPEC.rules.map((r) => `- ${r}`).join('\n')}\n\nFull prompts for an image tool: \`apps/mobile/assets/meals/prompts.json\`.\n\n## Shots\n\n| | File | Recipe | Vessel | Shot |\n|---|---|---|---|---|\n${rows.join('\n')}\n`,
);

const missing = RECIPES.filter((r) => !found.has(r.id)).map((r) => r.id);
for (const p of problems) console.error(`✗ ${p}`);
console.log(`${found.size} of ${RECIPES.length} recipes have a valid photo.${missing.length ? ` Missing: ${missing.join(', ')}` : ''}`);
if (problems.length || (check && missing.length)) process.exit(1);
