/**
 * Prices checked by hand at a real store (D-011). Generated by
 * `npm run prices:import`; don't edit by hand. `null` means that store hasn't
 * been checked, so the app uses the labelled sample prices.
 */
import type { CheckedStore } from '../price-check';
import type { Retailer } from '../schemas';

export const CHECKED_PRICES: Record<Retailer, CheckedStore | null> = {
  trader_joes: null,
  walmart: null,
};
