/**
 * Store price check (D-011). Two commands:
 *
 *   npm run prices:sheet
 *     Writes a blank sheet (CSV) and a printable checklist per store into
 *     docs/price-check/. Fill the CSV at the store, e.g. in Google Sheets or Numbers.
 *
 *   npm run prices:import -- <trader_joes|walmart> <filled.csv> --checked-on YYYY-MM-DD --location "Trader Joe’s, Court St, Brooklyn NY"
 *     Validates every row and, only if the whole store is complete, writes
 *     packages/domain/src/fixtures/checked-prices.ts. Commit that file; the
 *     app then shows "store check" prices for 45 days.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CHECKED_PRICES, RETAILERS, RETAILER_LABEL, SHEET_COLUMNS, STORE_CHECK_FRESH_DAYS, STORE_CHECK_MAX_AGE_DAYS, STORE_SECTION_LABEL, importCheck, sheetRows, toCsv, type CheckedStore, type Retailer } from '@weekwell/domain';

const ROOT = join(import.meta.dirname, '..');
const OUT = join(ROOT, 'docs/price-check');
const [command, ...args] = process.argv.slice(2);
const esc = (s: string) => s.replace(/[&<>"]/gu, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] ?? c);

function sheet() {
  for (const retailer of RETAILERS) {
    const rows = sheetRows(retailer);
    writeFileSync(join(OUT, `${retailer}-sheet.csv`), toCsv(rows.map((r) => ({ ...r, aisle: STORE_SECTION_LABEL[r.aisle as keyof typeof STORE_SECTION_LABEL] ?? r.aisle })), SHEET_COLUMNS));
    const byAisle = new Map<string, typeof rows>();
    for (const r of rows) byAisle.set(r.aisle, [...(byAisle.get(r.aisle) ?? []), r]);
    const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(RETAILER_LABEL[retailer])} price check</title>
<style>body{font:16px/1.45 -apple-system,system-ui,sans-serif;margin:16px;max-width:720px}h1{font-size:24px}h2{font-size:18px;margin-top:24px;border-bottom:1px solid #ccc}
li{margin:6px 0;list-style:none}label{display:flex;gap:10px;align-items:flex-start}input{width:20px;height:20px;margin-top:2px}small{color:#555;display:block}</style></head><body>
<h1>${esc(RETAILER_LABEL[retailer])} price check</h1>
<p>${rows.length} items. For each one, write in the sheet: the product name as printed, the package amount and unit, and the shelf price (not a sale or member price). If the exact product isn’t sold, pick the closest one and add a note. Loose produce sold by weight: enter the price for 1 lb, with amount 1 and unit lb.</p>
${[...byAisle.entries()].map(([aisle, items]) => `<h2>${esc(STORE_SECTION_LABEL[aisle as keyof typeof STORE_SECTION_LABEL] ?? aisle)}</h2><ul>${items.map((r) => `<li><label><input type="checkbox"><span><b>${esc(r.item)}</b><small>Look for: ${esc(r.look_for)} · amount in ${esc(r.enter_amount_in)}</small></span></label></li>`).join('')}</ul>`).join('\n')}
</body></html>
`;
    writeFileSync(join(OUT, `${retailer}-checklist.html`), html);
    console.log(`${RETAILER_LABEL[retailer]}: ${rows.length} items → docs/price-check/${retailer}-sheet.csv and ${retailer}-checklist.html`);
  }
}

function flag(name: string): string {
  const i = args.indexOf(name);
  return i >= 0 ? (args[i + 1] ?? '') : '';
}

function importSheet() {
  const retailer = args[0] as Retailer;
  const file = args[1];
  if (!RETAILERS.includes(retailer) || !file) {
    console.error('usage: npm run prices:import -- <trader_joes|walmart> <filled.csv> --checked-on YYYY-MM-DD --location "Store, street, city ST"');
    process.exit(2);
  }
  const res = importCheck(readFileSync(file, 'utf8'), retailer, { checkedOn: flag('--checked-on'), location: flag('--location') });
  for (const w of res.warnings) console.warn(`⚠ ${w}`);
  if (!res.ok) {
    for (const e of res.errors) console.error(`✗ ${e}`);
    console.error('Nothing was written.');
    process.exit(1);
  }
  const next: Record<Retailer, CheckedStore | null> = { ...CHECKED_PRICES, [retailer]: res.store };
  const target = join(ROOT, 'packages/domain/src/fixtures/checked-prices.ts');
  writeFileSync(
    target,
    `/**
 * Prices checked by hand at a real store (D-011). Generated by
 * \`npm run prices:import\`; don't edit by hand. \`null\` means that store hasn't
 * been checked, so the app uses the labelled sample prices.
 */
import type { CheckedStore } from '../price-check';
import type { Retailer } from '../schemas';

export const CHECKED_PRICES: Record<Retailer, CheckedStore | null> = ${JSON.stringify(next, null, 2)};
`,
  );
  console.log(`✓ ${Object.keys(res.store.items).length} items checked at ${res.store.location} on ${res.store.checkedOn}.`);
  console.log(`  The app shows them as "store check" prices, marked older after ${STORE_CHECK_FRESH_DAYS} days, and goes back to sample prices after ${STORE_CHECK_MAX_AGE_DAYS} days.`);
  console.log('  Commit packages/domain/src/fixtures/checked-prices.ts to ship it.');
}

if (command === 'sheet') sheet();
else if (command === 'import') importSheet();
else {
  console.error('usage: price-check.ts sheet | import …');
  process.exit(2);
}
